apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: developer-gitops
spec:
  destination:
    namespace: developer-gitops
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    helm:
    path: manifest/charts/developer-argo
    repoURL: 'https://github.com/kmcolli/cluster-gitops.git'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
